### PR TITLE
Nanobsd 11.0

### PR DESCRIPTION
**Pull request by connorchang**
Make petabi customized nanobsd with pius installed.

### CODE REVIEW

**Comment by msk** [comment]
Will there be a separate configuration file for each version we release?

**Comment by connorchang** [comment]
We should use the same configuration file as long as nanobsd script remains the same. In this pull request, since it's a major change 10.0->11.0 so I name the file NANO-11.0 in order to remind me the FreeBSD based version.

**Comment by msk** [comment]
Wouldn't it be better to retain such information as a comment in the file? Creating a new file for each version will increase duplications of contents in the repository.

**Comment by connorchang** [comment]
okay, previously we have NANO as a kernel config file, so what I will do is renaming NANO-11.0 to NANO and adding comments to that file. Am I correct?

**Comment by msk** [comment]
Yes.

**Pull request merged**
